### ISSUE TITLE
SCUMMVM with neon support

### ISSUE THREAD

**Issue by ArminiusTux** [spleen1981/scummvm_libretro_legacy#1]
Dear @spleen1981,

I spotted your [recent neon instructions commit for SCUMMVM](https://github.com/scummvm/scummvm/commit/db6469306a5cb0cb2b95969525e58822051ef754).

Could I direct your attention also to [this bug report](https://bugs.scummvm.org/ticket/15096) - it would be nice to have overall neon support back in the next SCUMMVM release.

Grazie

**Comment by spleen1981** [comment]
Hi, this is just an old forgotten fork... you should refer to https://github.com/libretro/scummvm/ for the libretro core issues (I'm the maintainer of that port), or https://github.com/scummvm/scummvm/ for general scummvm issues. The NEON commit above refers to the libretro port, which has its own separated build system, while the open issue mentioned seems to refer to the main configure script, so it needs to be addressed to scummvm/scummvm team, which knows and handles that script.
